version: "3.4"
services:
  website:
    image: morganpapers/morganpapersdotorg
    ports:
      - 80:80
  nlp:
    image: morganpapers/automatedcontentcreation
    environment:
      ISLANDORA_PASSWORD: secretpw
